# Use the official Ubuntu image
FROM ubuntu:latest

# Set the working directory
WORKDIR /app

# Install Python and Git
RUN apt-get update && \
    apt-get install -y python3 python3-pip git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Clone the Git repository
RUN git clone https://github.com/mingfeisun/COMP64803-Responsible-Reproducible-AI.git

# Set the working directory to the desired path
WORKDIR /app/COMP64803-Responsible-Reproducible-AI

# Default command to run when starting the container
CMD ["bash"]
