FROM python:3.12

WORKDIR /app 

RUN git clone https://github.com/gabecol7/COMP64803-Responsible-Reproducible-AI.git

WORKDIR /app/COMP64803-Responsible-Reproducible-AI/cohort-2025/gabriel_colenso/Effective_Python/

RUN python3 -m pip install -r requirements.txt

CMD ["/bin/bash"] 